version: '3'
services:
  umbrel:
    build: 
        context: build
    environment:
      - NGINX_PORT=8090
      - INSTALL_PATH=/umbrel
      - DOCKER_BINARY=/usr/bin/docker
    volumes:
      - /var/lib/docker/volumes/umbrel/_data:/umbrel
      - /var/run/docker.sock:/var/run/docker.sock
